create table group_uni (id bigint generated by default as identity, name varchar(255), primary key (id));
create table id_card (number bigint generated by default as identity, student_id bigint, primary key (number));
create table optional_subject (id bigint generated by default as identity, subject_name varchar(255), primary key (id));
create table student (id bigint generated by default as identity, last_name varchar(255), name varchar(255), group_uni_id bigint, primary key (id));
create table student_optional_subject (student_id bigint not null, optional_subject_id bigint not null, primary key (student_id, optional_subject_id));
alter table id_card add constraint FKgwxo0l0p6s7ooryp3e0mmofo3 foreign key (student_id) references student;
alter table student add constraint FKt55qriotqo81f6ryh6dqxb2u0 foreign key (group_uni_id) references group_uni;
alter table student_optional_subject add constraint FKnqi6wafpjlbccmipeawj4f5a foreign key (optional_subject_id) references optional_subject;
alter table student_optional_subject add constraint FKj5xodl1mjau8coj9ah6f6od86 foreign key (student_id) references student;