create table group_uni (id bigint generated by default as identity, name varchar(255), primary key (id));
create table group_uni_group_students (group_uni_id bigint not null, group_students_id bigint not null, primary key (group_uni_id, group_students_id));
create table id_card (number bigint generated by default as identity, student_id bigint, primary key (number));
create table optional_subject (id bigint generated by default as identity, subject_name varchar(255), primary key (id));
create table optional_subject_students (optional_subject_id bigint not null, students_id bigint not null, primary key (optional_subject_id, students_id));
create table student (id bigint generated by default as identity, last_name varchar(255), name varchar(255), group_uni_id bigint, primary key (id));
create table student_optional_subject (student_id bigint not null, optional_subject_id bigint not null, primary key (student_id, optional_subject_id));

alter table group_uni_group_students add constraint UK_mw3dwrcusm2dk8plmv66s5n30 unique (group_students_id);
alter table group_uni_group_students add constraint FKsfv0p1mam8hru31xw3puldskw foreign key (group_students_id) references student;
alter table group_uni_group_students add constraint FKiw0xnud89n8xwr7pbygmidoe6 foreign key (group_uni_id) references group_uni;

alter table id_card add constraint FKgwxo0l0p6s7ooryp3e0mmofo3 foreign key (student_id) references student;

alter table optional_subject_students add constraint FK7hpwyusbnapgsjkny4d4sqbej foreign key (students_id) references student;
alter table optional_subject_students add constraint FKcjaoh4hmrxnlk0kt787xxljhr foreign key (optional_subject_id) references optional_subject;

alter table student add constraint FKt55qriotqo81f6ryh6dqxb2u0 foreign key (group_uni_id) references group_uni;
alter table student_optional_subject add constraint FKnqi6wafpjlbccmipeawj4f5a foreign key (optional_subject_id) references optional_subject;
alter table student_optional_subject add constraint FKj5xodl1mjau8coj9ah6f6od86 foreign key (student_id) references student;